name: Build Base Image

permissions:
  contents: read
  packages: write

on:
  push:
    paths:
      - 'Dockerfile.base'
  workflow_dispatch:
  schedule:
    # Пересобираем базовый образ раз в неделю
    - cron: '0 2 * * 0'

jobs:
  build-base:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push base image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.base
        push: true
        tags: |
          ghcr.io/zagir2000/linguaai-base:latest
          ghcr.io/zagir2000/linguaai-base:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
