name: Deploy to Production Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Build application
      run: |
        go mod download
        go mod verify
        go build -o bin/lingua-ai ./cmd/main.go
        
    - name: Run tests
      run: |
        go test ./...
        
    - name: Deploy to server
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Останавливаем текущий сервис
          sudo systemctl stop lingua-ai || true
          
          # Создаем директорию для приложения
          sudo mkdir -p /opt/lingua-ai
          sudo chown $USER:$USER /opt/lingua-ai
          
          # Копируем новый бинарный файл
          cp bin/lingua-ai /opt/lingua-ai/
          chmod +x /opt/lingua-ai/lingua-ai
          
          # Создаем systemd сервис
          sudo tee /etc/systemd/system/lingua-ai.service > /dev/null <<EOF
          [Unit]
          Description=Lingua AI Telegram Bot
          After=network.target postgresql.service
          Requires=postgresql.service
          
          [Service]
          Type=simple
          User=root
          WorkingDirectory=/opt/lingua-ai
          ExecStart=/opt/lingua-ai/lingua-ai
          Restart=always
          RestartSec=10
          EnvironmentFile=/opt/lingua-ai/.env
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          # Перезагружаем systemd и запускаем сервис
          sudo systemctl daemon-reload
          sudo systemctl enable lingua-ai
          sudo systemctl start lingua-ai
          
          # Проверяем статус
          sudo systemctl status lingua-ai
          
          # Ждем запуска и проверяем webhook
          sleep 10
          curl -f http://localhost:8080/health || exit 1